// Scans public/assets/ and writes src/art-manifest.js listing what exists.
//
// The game must never request art that is not there: a 404 logs a console error,
// which the e2e suite treats as a failure, and it wastes a round trip on a cold
// PWA start. So instead of probing candidate paths at runtime, the build scans
// the folder once and bundles the result.
import { readdirSync, writeFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const ASSET_ROOT = 'public/assets';
const OUT = 'src/art-manifest.js';
const INDEX = 'public/art-index.json';

function walk(dir, acc = []) {
  let entries;
  try { entries = readdirSync(dir); } catch { return acc; }
  for (const name of entries) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full, acc);
    else acc.push(relative(ASSET_ROOT, full).split(sep).join('/'));
  }
  return acc;
}

export function scanArt() {
  const files = walk(ASSET_ROOT).sort();
  // Vite serves public/ at the root, so drop the leading "assets/" prefix that
  // we only used to locate the folder on disk.
  const paths = files
    .filter((f) => !/(^|\/)README\.txt$/i.test(f))
    .map((f) => `assets/${f}`);
  const body = `// GENERATED by scripts/scan-art.mjs — do not edit by hand.
// Lists every file present under public/assets/ so the loader can request only
// art that actually exists (no 404s, no console errors, no wasted requests).
export const ART_FILES = new Set(${JSON.stringify(paths, null, 2)});
`;
  writeFileSync(OUT, body);
  // The service worker cannot see src/, and it must precache the art for a
  // first-launch-offline start, so publish the same list as a static file.
  writeFileSync(INDEX, `${JSON.stringify(paths, null, 2)}\n`);
  return paths;
}

// Allow `node scripts/scan-art.mjs` for a manual refresh.
if (process.argv[1] && process.argv[1].endsWith('scan-art.mjs')) {
  const paths = scanArt();
  console.log(`[art] indexed ${paths.length} file(s) -> ${OUT}`);
}
